import { Platform, PlatformConfig } from '@/types'

export const platforms: Record<Platform, PlatformConfig> = {
  whatsapp: {
    id: 'whatsapp',
    name: 'WhatsApp',
    icon: 'whatsapp',
    primaryColor: '#25D366',
    secondaryColor: '#075E54',
    sentBubbleColor: '#DCF8C6',
    receivedBubbleColor: '#FFFFFF',
    sentTextColor: '#111111',
    receivedTextColor: '#111111',
  },
  imessage: {
    id: 'imessage',
    name: 'iMessage',
    icon: 'message-circle',
    primaryColor: '#007AFF',
    secondaryColor: '#5AC8FA',
    sentBubbleColor: '#007AFF',
    receivedBubbleColor: '#E9E9EB',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#000000',
  },
  instagram: {
    id: 'instagram',
    name: 'Instagram',
    icon: 'instagram',
    primaryColor: '#E4405F',
    secondaryColor: '#833AB4',
    sentBubbleColor: '#3797F0',
    receivedBubbleColor: '#EFEFEF',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#000000',
  },
  messenger: {
    id: 'messenger',
    name: 'Messenger',
    icon: 'message-circle',
    primaryColor: '#0084FF',
    secondaryColor: '#00C6FF',
    sentBubbleColor: '#0084FF',
    receivedBubbleColor: '#F0F0F0',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#000000',
  },
  telegram: {
    id: 'telegram',
    name: 'Telegram',
    icon: 'send',
    primaryColor: '#0088CC',
    secondaryColor: '#29B6F6',
    sentBubbleColor: '#EFFDDE',
    receivedBubbleColor: '#FFFFFF',
    sentTextColor: '#000000',
    receivedTextColor: '#000000',
  },
  discord: {
    id: 'discord',
    name: 'Discord',
    icon: 'hash',
    primaryColor: '#5865F2',
    secondaryColor: '#7289DA',
    sentBubbleColor: '#5865F2',
    receivedBubbleColor: '#2F3136',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#DCDDDE',
  },
  slack: {
    id: 'slack',
    name: 'Slack',
    icon: 'hash',
    primaryColor: '#4A154B',
    secondaryColor: '#611F69',
    sentBubbleColor: '#FFFFFF',
    receivedBubbleColor: '#FFFFFF',
    sentTextColor: '#1D1C1D',
    receivedTextColor: '#1D1C1D',
  },
  signal: {
    id: 'signal',
    name: 'Signal',
    icon: 'shield',
    primaryColor: '#3A76F0',
    secondaryColor: '#2C6BED',
    sentBubbleColor: '#3A76F0',
    receivedBubbleColor: '#F0F0F0',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#000000',
  },
  snapchat: {
    id: 'snapchat',
    name: 'Snapchat',
    icon: 'ghost',
    primaryColor: '#FFFC00',
    secondaryColor: '#FFE600',
    sentBubbleColor: '#8B5CF6',
    receivedBubbleColor: '#E5E5E5',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#000000',
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    icon: 'music',
    primaryColor: '#000000',
    secondaryColor: '#FE2C55',
    sentBubbleColor: '#FE2C55',
    receivedBubbleColor: '#2F2F2F',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#FFFFFF',
  },
  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    icon: 'twitter',
    primaryColor: '#1DA1F2',
    secondaryColor: '#14171A',
    sentBubbleColor: '#1DA1F2',
    receivedBubbleColor: '#E1E8ED',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#14171A',
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: 'linkedin',
    primaryColor: '#0A66C2',
    secondaryColor: '#004182',
    sentBubbleColor: '#0A66C2',
    receivedBubbleColor: '#F3F2EF',
    sentTextColor: '#FFFFFF',
    receivedTextColor: '#000000',
  },
}

export const platformList = Object.values(platforms)

export const getPlatformConfig = (platform: Platform): PlatformConfig => {
  return platforms[platform]
}
